apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-postgres-config
  namespace: default  
data:
  conf.yaml: |
    init_config:

    instances:
      - dbm: true
        host: my-rds.eu-west-1.rds.amazonaws.com
        port: 5432
        username: postgres
        password: 'bX3bH9LDtFDqxpkY48Df'
