name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 instance and prepare for deployment
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Ensure Docker and docker-compose are ready
            node --version
          EOF

      - name: Copy source to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          scp -o StrictHostKeyChecking=no -r * $EC2_USER@$EC2_HOST:/home/projects/item-tray

      - name: Execute Docker commands on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            ls
            echo "success"

            cd /home/projects/item-tray
            cat a.txt

          EOF

      - name: Install dependencies and build project
        env:
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USER: ${{ secrets.EC2_USER }}
        run: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'

            cd /home/projects/item-tray
            sudo rm -rf node_modules
            npm install
            #npm run build

            echo "Dependencies installed and project built successfully"
            EOF

      - name: Create System Configuration (Service)
        env:
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USER: ${{ secrets.EC2_USER }}
        run: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << "EOF"

            echo "Creating System Configuration (Service)"
            echo "----------------------------------------------------------------"
        
            # Check and configure systemd service
            if [[ ! -f "/etc/systemd/system/itemtray.service" ]]
            then
                    
            sudo chmod -R 777 /etc/systemd/system
            sudo cat >> /etc/systemd/system/itemtray.service <<EOL

            [Unit]
            Description=itemtray

            After=network.target

            [Service]
            SyslogIdentifier=itemtray
            User=www-data
            WorkingDirectory=/home/ubuntu/projects/itemtray
            ExecStart=/usr/bin/npm run start
            Environment="PORT=3060"
            Restart=on-failure
            RestartSec=10
            KillSignal=SIGINT


            [Install]
            WantedBy=multi-user.target
            EOL

            sudo systemctl enable itemtray.service
            fi
            sudo systemctl stop itemtray.service